### ISSUE TITLE
subtrac --auto-exclude panics when trying to resolve deleted submodules

### ISSUE THREAD

**Issue by ccmtaylor** [apenwarr/git-subtrac#3]
this is a follow-up of #2; I added a commit to ccmtaylor/subtrac-test to remove the submodule.

git-subtrac is unable to resolve submodules that have been removed in the current branch. Not sure if this is expected; maybe git-subtrac needs to look at a previous version of `.gitignore`?

```
$ git clone https://github.com/ccmtaylor/subtrac-test --recurse-submodules
Cloning into 'subtrac-test'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 7 (delta 0), reused 7 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.

$ cd subtrac-test

$ git subtrac -v update
Scanning branch: refs/heads/master
  add 4f0f106d83 refs/heads/master/
Searching submodules for: refs/heads/master~1/cookbooks/apache2@7b9de411db
git-subtrac: refs/heads/master~1/cookbooks/apache2@7b9de411db: 7b9de411dbefb628f8ac779b971da96d915ab86c not found. (fetch it manually? or try --exclude)
```

However, when I run git-subtrac with the `--auto-exclude` flag, it panics with a SIGSEGV:

```
$ git subtrac -v --auto-exclude update
Scanning branch: refs/heads/master
  add 4f0f106d83 refs/heads/master/
Searching submodules for: refs/heads/master~1/cookbooks/apache2@7b9de411db
Excluding 7b9de411dbefb628f8ac779b971da96d915ab86c
  add fbdc2a594f refs/heads/master~1/cookbooks/
  add 8d1c14bc25 refs/heads/master~1/
  add e17b5a0633 refs/heads/master~1
  add c89b104d9a refs/heads/master
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x783dc8]

goroutine 1 [running]:
main.(*Cache).UpdateBranchRefs(0xc000021a40, 0x1, 0xc000093f80)
	/home/christophertaylor/src/github.com/apenwarr/git-subtrac/subtrac.go:155 +0x278
main.main()
```

**Comment by ccmtaylor** [comment]
I suspect it's due to this error check: https://github.com/apenwarr/git-subtrac/blob/31394d85ecb199fba4cb48f690e72f82f20a28bc/subtrac.go#L179-L182

If `tc` _and_ `err` are `nil`, the function returns `nil, nil`, and `UpdateBranchRefs` will insert a `nil` in the commits slice: https://github.com/apenwarr/git-subtrac/blob/31394d85ecb199fba4cb48f690e72f82f20a28bc/subtrac.go#L140-L146

That leads to the nil dereference here: https://github.com/apenwarr/git-subtrac/blob/31394d85ecb199fba4cb48f690e72f82f20a28bc/subtrac.go#L155

**Comment by apenwarr** [comment]
Fixed. Thanks for reporting!
