### ISSUE TITLE
Readme installation instructions (go install) don't work

### ISSUE THREAD

**Issue by nyanpasu64** [apenwarr/git-subtrac#6]
Windows 10 x64. I just installed Go through the .msi installer.

This project's readme tells me to run `go install github.com/apenwarr/git-subtrac`. It doesn't work.

> can't load package: package github.com/apenwarr/git-subtrac: cannot find package "github.com/apenwarr/git-subtrac" in any of:
>         c:\go\src\github.com\apenwarr\git-subtrac (from $GOROOT)
>         C:\Users\nyanpasu\go\src\github.com\apenwarr\git-subtrac (from $GOPATH)

I have to run `go get github.com/apenwarr/git-subtrac` first, which takes several minutes and produces no terminal output whatsoever. Afterwards, `go install github.com/apenwarr/git-subtrac` is instant. I don't know if it's necessary or not.

Now running git-subtrac outputs `git-subtrac: git: 0xc0000e65c0: repository does not exist` outside of a repo, and provides a help message within a repository.

**Comment by apenwarr** [comment]
I've improved the instructions to refer to 'go get'. I'm specifically mentioning 'go get -v' (verbose), which prints more interesting output while it runs, so you know it's alive.
